Fix import error when missing dependencies
Trying to use without either Selenium or Playwright packages installed:
ModuleNotFoundError: No module named 'selenium'.